# Generated by Django 3.0.6 on 2020-05-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('N', 'Normal'), ('L', 'Low')], max_length=1),
        ),
    ]
